In [2]:
print("Hello World")


Hello World


Hello

In [3]:
import pandas as pd
p = pd.array([2,3])
print(p)

<IntegerArray>
[2, 3]
Length: 2, dtype: Int64


Pandas 2D array

In [4]:
import pandas as pd
p=pd.array([[1,2],[3,4]])

print(p)

<NumpyExtensionArray>
[[1, 2], [3, 4]]
Length: 2, dtype: object


Numpy array

In [5]:
import numpy as np
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
a=np.array([1,2,3,4],dtype='int64')
print(a)

[1 2 3 4]


In [7]:
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.shape)

1
int64
4
8
32
(4,)


In [8]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
print(b.ndim)
print(b.dtype)
print(b.size)
print(b.itemsize)
print(b.nbytes)
print(b.shape)

2
int64
8
8
64
(2, 4)


In [10]:
c = np.zeros((4,5),dtype='int32')
d = np.ones((2,3),dtype='int32')
e = np.full((5,6),7)
print(c)
print(d)
print(e)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1]
 [1 1 1]]
[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [11]:
f = np.full_like(b,69)
print(f)

[[69 69 69 69]
 [69 69 69 69]]


In [12]:
print(np.arange(4))
print(np.arange(2,9))
print(np.arange(2,9,2))
print(np.linspace(2,10,5, dtype='int32'))
print(np.linspace(2,10,9 , dtype='int'))

[0 1 2 3]
[2 3 4 5 6 7 8]
[2 4 6 8]
[ 2  4  6  8 10]
[ 2  3  4  5  6  7  8  9 10]


In [13]:
g= np.random.rand(3,4)
h= np.random.randint(5,10 , size=b.shape)
i= np.identity(5,dtype='int32')
j=np.linspace(2,10,5)
print(g)
print(h)
print(i)
print(j)

[[0.81601844 0.78840667 0.09184456 0.082554  ]
 [0.17749687 0.0850765  0.14757314 0.57022094]
 [0.72073826 0.99687623 0.87876899 0.84482763]]
[[6 5 6 9]
 [5 5 7 6]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[ 2.  4.  6.  8. 10.]


In [14]:
#Repeat an array
brr=np.array([[1,2,3]])
k=np.repeat(brr,3,axis=0)
l=np.repeat(brr,3,axis=1)
mrr=np.array([[[1],[2],[3]]])
m=np.repeat(mrr,3,axis=2)

print(k)
print(l)
print(m)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]
[[[1 1 1]
  [2 2 2]
  [3 3 3]]]


Statistics

In [15]:
st=np.array([[1,2,3],[4,5,6]])
st

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
print(st)
print(np.min(st))
print(np.max(st))
print(np.min(st,axis=0))
print(np.max(st,axis=0))
print(np.min(st,axis=1))
print(np.max(st,axis=1))

[[1 2 3]
 [4 5 6]]
1
6
[1 2 3]
[4 5 6]
[1 4]
[3 6]


In [17]:
print(st)
print(np.sum(st))
print(np.sum(st,axis=0))
print(np.sum(st,axis=1))

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


Reorganizng arrays

In [24]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print()

arr1=arr.reshape((4,2))
print(arr1)
print()

print(np.reshape(arr, newshape=(2,2,2)))
print()

arr2 = np.array([[99,100],[101,102]])
print(arr2)
print()

arr3 = np.array([[4,3,2,1],[8,7,6,5]])
print(arr3)
print()

arr4=np.vstack((arr,arr3))
print(arr4)
print()
print(np.hstack((arr,arr2)))
print()
print(np.hstack((arr,arr3,arr2)))
print()

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[ 99 100]
 [101 102]]

[[4 3 2 1]
 [8 7 6 5]]

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]

[[  1   2   3   4  99 100]
 [  5   6   7   8 101 102]]

[[  1   2   3   4   4   3   2   1  99 100]
 [  5   6   7   8   8   7   6   5 101 102]]



In [19]:
p=arr4
print(p)

print(p[p<4])
print(p<4)
print(p%2==0)

[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]
 [8 7 6 5]]
[1 2 3 3 2 1]
[[ True  True  True False]
 [False False False False]
 [False  True  True  True]
 [False False False False]]
[[False  True False  True]
 [False  True False  True]
 [ True False  True False]
 [ True False  True False]]
