In [1]:
import numpy as np

Matrix multiplication using numpy

In [2]:
def mat_multi(a,b):
    ans=np.zeros((len(a),len(b[0])),dtype='int64')
    b2=np.transpose(b)
    for i in range(len(a)):
        for j in range(len(b2)):
            ans[i,j]=np.dot(a[i],b2[j])
    return ans

Matrix multiplication without numpy

In [3]:
#Transpose of an array

def trans(a):
    ans=[[0 for i in range(len(a))] for j in range(len(a[0]))]
    for i in range(len(ans)):
        for j in range(len(ans[0])):
            ans[i][j]= a[j][i]
    return ans

In [4]:
#Dot product

def dp(a,b):
    res=0
    for i in range(len(a)):
        res+=a[i]*b[i]
    return res

In [5]:
# Matrix Multiplication

def mat_mup(a,b):
    new=[[0 for i in range(len(b[0]))] for j in range(len(a))]
    b2=trans(b)
    for i in range(len(a)):
        for j in range(len(b2)):
            new[i][j]= dp(a[i],b2[j])
    return new

In [6]:
# Matrices to be multiplied

a=[[1,2,3],[4,5,6]]
b=[[1,2],[3,4],[5,6]]

Numpy in-built

In [7]:
print(np.matmul(a,b))

[[22 28]
 [49 64]]


Numpy user defined

In [8]:
temp = np.array(mat_multi(a,b))
print(temp)

[[22 28]
 [49 64]]


Without numpy

In [9]:
temp2=np.array(mat_mup(a,b))
print(temp2)

[[22 28]
 [49 64]]
